Readme update from issue #1
SpaceyaTech/Team-Berlin-Django pull request #2
Opened 2022-10-30 09:56 UTC by MalonzaElkanah

Worked on Installation guide and Running guide.

2022-10-30 10:08 UTC, Barissa-Imran requested changes

2022-10-30 10:08 UTC, Barissa-Imran commented on README.md
> +If you find an issue that you want to work on, comment on it to have it assigned to you;
- Suggest collaborators create their own issue and upon approval work on it
- Suggest that collaborators should only claim an issue when they are familiar with the code base and can work on it

2022-10-30 10:08 UTC, Barissa-Imran commented on README.md
> +2. Create a branch and start working on your changes!
- collaborators should rebase the pre-dev branch when creating branches. (This is where new code will be merged)
```bash
git branch newbranch pre-dev
```
or
```bash
git checkout -b newbranch pre-dev
```
or 

on GitHub, select the pre-dev branch in your fork then create a branch (it should tell you that you're rebasing the pre-dev branch)

2022-10-30 10:09 UTC, Barissa-Imran commented
Hi @MalonzaElkanah , I have made some comments on things to add.

Otherwise LGTM

2022-11-02 08:23 UTC, jumalaw98 commented on README.md
> +If you find an issue that you want to work on, comment on it to have it assigned to you;
Sorry for late review of this, am glad for your update

2022-11-02 08:26 UTC, merged

2022-11-02 08:31 UTC, jumalaw98 commented
@Barissa-Imran @MalonzaElkanah  can you make update, on the collaboration part: 

Forking the main repo
Check out `pre-dev` branch and pull the updates from it which is the collaboration branch 

Whats your take on this

2022-11-02 08:37 UTC, Barissa-Imran commented
This should work but increases errors and the number of commits from collaborators and repo managers. Have to sync the repos which can be problematic when main is ahead of the development branches. Creates a loop of commits. (after committing you're asked to update the branch and loops like that). But I don't know